spring.application.name=click-sala

# PostgreSQL database connection properties
spring.datasource.url=jdbc:postgresql://postgres:5432/click_sala
spring.datasource.username=admin
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=update

# JWT configuration
jwt.secret=chaveSuperSecreta123456
jwt.expiration=3600000
