spring.application.name=click-sala

# PostgreSQL database connection properties
spring.datasource.url=jdbc:postgresql://postgres:5432/click_sala
spring.datasource.username=admin
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=update

# JWT configuration
jwt.secret=K9r8Us7Pd6VbTq2Xc5AfGhLmNzYwErTi
jwt.expiration=3600000

logging.level.org.hibernate=DEBUG
